```{r include=FALSE}
library(ggplot2)
library(ggrepel)
library(plotly)
library(scales)
library(ggpubr)
```



```{r include=FALSE}
data=read.csv("DataFinal.csv")
```

###Desempeño en la red y votos válidos

```{r include=FALSE}
names(data)
```

```{r include=FALSE}
data$Nuevos_Followers=data$Telecciones - data$TAfterDeb
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
x <- data$candidato
hovertxt <- paste("Candidato:", x)

d <- ggplot(data, aes(x=Nuevos_Followers, y=validos, size=totEngagementFB, color=totEngagementFB,text = hovertxt)) + geom_point()  + ggtitle("Crecieron los candidatos en la red luego del primer debate?") + ylab("% votos validos") + xlab("Nuevos Followers en Twitter (debate hasta elecciones)") + geom_label_repel(aes(label = candidato), segment.color = 'grey50',size=3) + 
scale_color_gradient(low = '#fcae91', high = '#a50f15', labels = comma)

ggplotly(d)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
x <- data$candidato
hovertxt <- paste("Candidato:", x)

d <- ggplot(data, aes(x=Nuevos_Followers, y=ipsos, size=totEngagementFB, color=totEngagementFB,text = hovertxt)) + geom_point()  + ggtitle("Crecieron los candidatos en la red luego del primer debate?") + ylab("% votos validos") + xlab("Nuevos Followers en Twitter (debate hasta elecciones)") + geom_label_repel(aes(label = candidato), segment.color = 'grey50',size=3) + 
scale_color_gradient(low = '#fcae91', high = '#a50f15', labels = comma)

ggplotly(d)
```


```{r include=FALSE}
data=read.csv("dataAfertdep.csv")
data1=data[,c(3,14)]
data1$periodo=1
names(data1)=c('candidato','seguidoresNuevos',"periodo")
data2=data[,c(3,15)]
data2$periodo=2
names(data2)=names(data1)
dataLong=rbind(data1,data2)
labels <- c('1'="Antes del primer debate (sólo setiembre)", '2'="Entre primer y segundo debate")
dataLong$periodo <- ordered(dataLong$periodo, labels =labels,
                            levels=c(1,2))
```


```{r include=FALSE}
library(forcats)
g <- ggplot(data=dataLong,
            aes(x=fct_rev(candidato),y=seguidoresNuevos)) + geom_bar(stat="identity")
g +     coord_flip() + facet_wrap( ~ periodo,scales="free_x") + ylim(0, 4000) + ylab("Nuevos Seguidores") + xlab("")
```


```{r include=FALSE}
g <- ggplot(data=data,
        aes(x=reorder(candidato, Nuevos_Followers1), y=Nuevos_Followers1,group=1)) +
  geom_bar(stat="identity") + xlab("") + ylab("Nuevos Followers")+
    theme(text = element_text(size=9))+ coord_flip() + ggtitle("Entre 01/09 al 23/09 (antes debate 1)") +
  ylim(0, 4000)
```

```{r include=FALSE}
d <- ggplot(data=data,
       aes(x=reorder(candidato, Nuevos_Followers2), y=Nuevos_Followers2,group=1)) +
  geom_bar(stat="identity") + xlab("") + ylab("Nuevos Followers")+
    theme(text = element_text(size=9))+ coord_flip() + ggtitle("Entre 24/09 al 29/09 (antes debate 2)")+
  ylim(0, 4000)
```

```{r include=FALSE}
ggarrange(g, d ,
          ncol = 2, nrow = 1)
```


```{r include=FALSE}
ggplot(data[data$setiembre >0,], aes(x=Nuevos_Followers2, y=setiembre, size=following_afdeb, color=antiguedad)) + geom_point()  + ggtitle("Han crecido los candidatos en la red luego del primer debate?") + ylab("% Intencion de voto") + xlab("Nuevos Followers") + geom_label_repel(aes(label = candidato), segment.color = 'grey50',size=3,box.padding= unit(0.4, "lines")) + scale_size(labels = comma)#  + 
# scale_color_gradient(low = '#fcae91', high = '#a50f15') + theme(
# panel.grid.minor = element_blank() 
# 
# )

```

```{r include=FALSE}

x <- data[data$setiembre >0,]$candidato
hovertxt <- paste("Candidato:", x)

graph <- ggplot(data[data$setiembre >0,], aes(x=Nuevos_Followers2, y=setiembre, size=following_afdeb, color=antiguedad,text = hovertxt))+ geom_point() + ggtitle("Han crecido los candidatos en la red luego del debate?") + ylab("% Intencion de voto") + xlab("Nuevos Followers") + 
scale_color_gradient(low = '#fcae91', high = '#a50f15')

p <- ggplotly(graph)

p
```
